CREATE TABLE USUARIO (
	ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(150) NOT NULL
)

INSERT INTO USUARIO (LOGIN, SENHA) VALUES ('master', 'teste1234');

CREATE TABLE TAREFA_STATUS (
	ID INTEGER NOT NULL PRIMARY KEY,
	NOME_STATUS VARCHAR(150) NOT NULL
);

INSERT INTO TAREFA_STATUS (ID, NOME_STATUS) 
VALUES
(1,'CRIADO'), (2, 'ATIVO'), (3, 'PENDENTE'), (4, 'FINALIZADO'), (5,'CANCELADO');


CREATE TABLE TAREFAS (
	ID INTEGER NOT NULL IDENTITY PRIMARY KEY,
	NOME_TAREFA VARCHAR(100) NOT NULL,
	STATUS INTEGER NOT NULL,
	DATA_FINALIZACAO DATETIME NULL,
	PRIORIDADE VARCHAR(10) NOT NULL,
	
	CHECK (PRIORIDADE IN('Normal', 'Média', 'Alta')),

	FOREIGN KEY (STATUS) REFERENCES TAREFA_STATUS(ID)
);

CREATE TRIGGER TR_TAREFAS ON TAREFAS AFTER UPDATE
AS
BEGIN
	IF (SELECT STATUS FROM INSERTED) IN (4,5)
		UPDATE TAREFAS SET DATA_FINALIZACAO = GETDATE() WHERE ID = (SELECT ID FROM INSERTED);
END



